# Generated by Django 5.0 on 2023-12-26 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyblademasterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beyblademasterapp.mentor'),
        ),
    ]
