# Generated by Django 5.0 on 2023-12-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyblademasterapp', '0002_alter_player_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='beyblade',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/images'),
        ),
    ]
