# Generated by Django 5.0 on 2023-12-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyblademasterapp', '0003_beyblade_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='beyblade',
            name='type',
            field=models.CharField(blank=True, choices=[('Balance', 'Balance'), ('Defense', 'Defense'), ('Attack', 'Attack'), ('Stamina', 'Stamina')], max_length=100, null=True),
        ),
    ]
